Forgot to change function names

diff --git a/functions/install_thirdparty b/functions/install_thirdparty
--- a/functions/install_thirdparty
+++ b/functions/install_thirdparty
@@ -5,45 +5,50 @@
 
 # Automatically import apps functions
 function import_apps_functions {
-	DIR="functions/apps"
-	# iterate through the files in the 'functions/apps' folder
-	for FUNCTION in $(dirname "$0")/$DIR/*; do
-		if [[ -d $FUNCTION ]]; then
-			continue
-		elif [[ -f $FUNCTION ]]; then
-			# source the function file
-			. $FUNCTION
-		fi
-	done
+    DIR="functions/apps"
+    # iterate through the files in the 'functions/apps' folder
+    for FUNCTION in $(dirname "$0")/$DIR/*; do
+        if [[ -d $FUNCTION ]]; then
+            continue
+        elif [[ -f $FUNCTION ]]; then
+            # source the function file
+            . $FUNCTION
+        fi
+    done
 }
 
 # Install Third-Party Applications
 function install_thirdparty {
-	NAME="Third-Party Software"
-	echo_message title "Starting installation of ${NAME,,}..."
-	import_apps_functions
-	# Draw window
-	THIRDPARTY=$(eval `resize` && whiptail \
-		--notags \
-		--title "Install $NAME" \
-		--menu "\nWhat ${NAME,,} would you like to install?" \
-		--ok-button "Install" \
-		--cancel-button "Go Back" \
-		$LINES $COLUMNS $(( $LINES - 12 )) \
-		'install_chrome'        'Google Chrome' \
-		'install_dropbox'       'Dropbox' \
-		'install_oracle_java'   'Oracle Java' \
-		'install_rvm'           'Ruby Version Manager (RVM)' \
-		'install_sublime_text'  'Sublime Text 3' \
-		3>&1 1>&2 2>&3)
+    NAME="Third-Party Software"
+    echo_message title "Starting installation of ${NAME,,}..."
+    import_apps_functions
+    # Draw window
+    THIRDPARTY=$(eval `resize` && whiptail \
+            --notags \
+            --title "Install $NAME" \
+            --menu "\nWhat ${NAME,,} would you like to install?" \
+            --ok-button "Install" \
+            --cancel-button "Go Back" \
+            $LINES $COLUMNS $(( $LINES - 12 )) \
+            'install_chrome'        'Google Chrome' \
+            'install_dropbox'       'Dropbox' \
+            'install_oracle_java'   'Oracle Java' \
+            'install_rvm'           'Ruby Version Manager (RVM)' \
+            'install_sublime_text'  'Sublime Text 3' \
+            'install_atom'  'Atom' \
+            'install_nnn'  'nnn' \
+            'install_nextcloud-client'  'NextCloud Client' \
+            'install_remmina-next'  'Remmina (next)' \
+            'install_google-drive-ocamlfuse'  'FUSE filesystem over Google Drive' \
+        3>&1 1>&2 2>&3)
 
-	# check exit status
-	if [ $? = 0 ]; then
-		echo_message header "Starting '$THIRDPARTY' function..."
-		$THIRDPARTY
-	else
-		# Cancelled
-		echo_message info "Installation of ${NAME,,} cancelled."
-		main
-	fi
+    # check exit status
+    if [ $? = 0 ]; then
+        echo_message header "Starting '$THIRDPARTY' function..."
+        $THIRDPARTY
+    else
+        # Cancelled
+        echo_message info "Installation of ${NAME,,} cancelled."
+        main
+    fi
 }
