Remove ppa: prefix PPA third party installers

diff --git a/functions/apps/papirus_icon_theme b/functions/apps/papirus_icon_theme
--- a/functions/apps/papirus_icon_theme
+++ b/functions/apps/papirus_icon_theme
@@ -17,35 +17,20 @@ function install_papirus_icon_theme {
     NAME="Papirus Icon Theme"
     PACKAGE=papirus-icon-theme
     PACKAGE_ADD="papirus-folders filezilla-theme-papirus libreoffice-style-papirus"
-    PPA=papirus/papirus
-    # Install
-    echo_message header 'Begin '$NAME' installation'
-    # Check if package is installed
-    check_package $PACKAGE
-    EXITSTATUS=$?
-    # If package is not installed
-    if [ $EXITSTATUS = 1 ]; then
-        echo_message info $NAME 'is not installed.'
-        echo 'Proceeding'
-        # Add repository
-        echo_message info 'Adding '$NAME' repository to software sources...'
-        elevate_privilege "add-apt-repository -y $PPA"
-        # Update repository information
-        echo_message info 'Updating repository information...'
-        elevate_privilege "apt update -y"
-        echo_message success 'Done.'
-        # Install
-        echo_message info 'Installing '$NAME'...'
-        elevate_privilege "apt install -y $PACKAGE"
-        elevate_privilege "apt install -y $PACKAGE_ADD"
-        # Done
-        echo_message success "Installation of '$PACKAGE' complete."
-        whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
-        install_thirdparty
-    else
-        # Already installed
-        echo_message info $NAME 'already installed.'
-        whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
-        install_thirdparty
-    fi
+    PPA=papirus/papirus-dev
+
+  	# Add PPA repository
+  	add_launchpad_ppa "$NAME" "$PPA" install_thirdparty
+  	# check exit status
+  	if [ $? = 0 ]; then
+  		# Install package
+  		install_package "$NAME" "$PACKAGE" install_thirdparty
+  		install_package "$NAME extra" "$PACKAGE_ADD" install_thirdparty
+  	else
+  		# Cancelled
+  		echo_message info "Installation of $NAME cancelled."
+  		# return
+  		install_thirdparty
+  	fi
+
 }
