Updating app functions

diff --git a/functions/apps/remmina-next b/functions/apps/remmina-next
--- a/functions/apps/remmina-next
+++ b/functions/apps/remmina-next
@@ -5,7 +5,7 @@
 # most of this template is complete, you'll just need to change the three variables and the function name
 #
 #	package_name = the name of the package you'll be installing from the PPA
-#	ppa_url = the url of the PPA in the form ppa:user/ppa
+#	ppa_url = the url of the PPA in the form user/ppa
 #	app_name = a human readable name of the app you're installing
 #
 # next set the 'function_name' and reference it in the 'install_thirdparty' function in the 'install_thirdparty' function file
@@ -16,34 +16,19 @@ function install_remmina {
     # Variables
     NAME="Remmina Next"
     PACKAGE=remmina
-    PPANAME=ppa:remmina-ppa-team/remmina-next
+    PPA=ppa:remmina-ppa-team/remmina-next
     # Install
     echo_message header 'Begin '$NAME' installation'
-    # Check if package is installed
-    check_package $PACKAGE
-    EXITSTATUS=$?
-    # If package is not installed
-    if [ $EXITSTATUS = 1 ]; then
-        echo_message info $NAME 'is not installed.'
-        echo 'Proceeding'
-        # Add repository
-        echo_message info 'Adding '$NAME' repository to software sources...'
-        elevate_privilege "add-apt-repository -y $PPANAME"
-        # Update repository information
-        echo_message info 'Updating repository information...'
-        elevate_privilege "apt update -y"
-        echo_message success 'Done.'
-        # Install
-        echo_message info 'Installing '$NAME'...'
-        elevate_privilege "apt install -y $PACKAGE"
-        # Done
-        echo_message success "Installation of '$PACKAGE' complete."
-        whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
-        install_thirdparty
+
+    add_launchpad_ppa "$NAME" "$PPA" install_thirdparty
+    # check exit status
+    if [ $? = 0 ]; then
+        # Install package
+        install_package "$NAME" "$PACKAGE" install_thirdparty
     else
-        # Already installed
-        echo_message info $NAME 'already installed.'
-        whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
+        # Cancelled
+        echo_message info "Installation of $NAME cancelled."
+        # return
         install_thirdparty
     fi
 }
